### ISSUE TITLE
v 1.1.1 breaks functional tests

### ISSUE THREAD

**Issue by leealexey** [Codeception/module-yii2#14]
My tests create some records in DB using AR between tests, but after upgrading to 1.1.1 records being removed after each test. All tests are passing on v. 1.1.0

**Comment by Naktibalda** [comment]
Try setting `transaction: false` in module parameters to keep the previous default behaviour:
```yaml
modules:
    enabled:
        - Yii2:
            transaction: false
```
