### ISSUE TITLE
No support php8.2

### ISSUE THREAD

**Issue by pamparam83** [Codeception/module-yii2#79]
my config
```json
"require-dev": {
        "codeception/codeception": "^5.0.0",
        "codeception/lib-innerbrowser": "^3.0",
        "codeception/module-asserts": "^3.0",
        "codeception/module-filesystem": "^3.0",
        "codeception/module-phpbrowser": "^3.0",
        "codeception/module-webdriver": "3.1.0",
        "codeception/module-yii2": "^1.1",
        "codeception/specify": "~0.4.6",
        "codeception/verify": "^2.2",
....
        }
 ```

 and console run 

 `php vendor/bin/codecept run functional`
 
 result
 ```
 In Configuration.php line 236:
                                                     
  Output path is not defined by key "paths: output"  
  ```

**Comment by Naktibalda** [comment]
If you upgraded to Codeception 5, you have to rename old `paths: log` setting to `paths: output` in codeception.yml file.

before:
```yaml
paths:
    tests: tests
    log: tests/log
```

after:
```yaml
paths:
    tests: tests
    output: tests/log
```
